#!/system/bin/sh
#
# simply include module to MODLIST; i.e. if you
# you have in /system/lib/modules a file xpad.ko
# append at end of list

MODLIST="cifs f2fs fat msdos ntfs vfat"

MODPROBE="/system/xbin/modprobe -v"

for mod in $MODLIST; do
    $MODPROBE $mod
done
