#!/system/bin/sh
#
# should be self-explaining:
# this is the file you put your tunings to
# file in /sys (sysfs) and /proc (procfs)

# set governor
# available governors:
# conservative ondemand interactive
# you can set this also in Settings->Performance->CPU
# echo ondemand >/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor

# tuning governor
# settings depend on used governor
# echo 90 >/sys/devices/system/cpu/cpufreq/interactive/target_loads
# for now to avoid oscellating strongly recommended!
echo 200000 >/sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq

# set multicore power savings
# 0 = disabled
# 1 = enabled
# 2 = aggressive
# echo 1 >/sys/devices/system/cpu/sched_mc_power_savings

# set sceduler
# you can set this also in Settings->Performance->I/O-Scheduler
# mmc0 for internal sdcard
# mmc2 for external sdcard
# echo bfq >/sys/devices/platform/dw_mmc.0/mmc_host/mmc0/mmc0\:0001/block/mmcblk0/queue/scheduler
# echo bfq >/sys/devices/platform/dw_mmc.2/mmc_host/mmc2/mmc2\:0001/block/mmcblk1/queue/scheduler
